import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const lots = [
      {
	id: 1,
	name: "Dell Letitude m5",
	currentPrice: 230,
	startPrice: 200,
	lastPrice: 300,
	img: [ "/assets/img/lots/lot1_1.jpg", "/assets/img/lots/lot1_2.jpg", "/assets/img/lots/lot1_3.jpg"],
	customer: "Alex",
	totalCustomers: 3,
	finishDate: 1,
	category: "notebook",
	subCategory: "dell",
	description: "Alot information about different features"
	},
	{
	id: 2,
	name: "Asus R512",
	currentPrice: 230,
	startPrice: 200,
	lastPrice: 300,
	img: [ "/assets/img/lots/lot2_1.jpg", "/assets/img/lots/lot2_2.jpg", "/assets/img/lots/lot2_3.jpg"],
	customer: "Dmitry",
	totalCustomers: 2,
	finishDate: 5,
	category: "notebook",
	subCategory: "asus",
	description: "Alot information about different features"
	},
	{
	id: 3,
	name: "Lenovo w12",
	currentPrice: 250,
	startPrice: 200,
	lastPrice: 300,
	img: [ "/assets/img/lots/lot3_1.jpg", "/assets/img/lots/lot3_2.jpg", "/assets/img/lots/lot3_3.jpg"],
	customer: "Bob",
	totalCustomers: 5,
	finishDate: 3,
	category: "notebook",
	subCategory: "lenovo",
	description: "Alot information about different features"
	},
	{
	id: 4,
	name: "Lenovo ideaPad",
	currentPrice: 50,
	startPrice: 0,
	lastPrice: 100,
	img: [ "/assets/img/lots/lot4_1.jpg", "/assets/img/lots/lot4_2.jpg", "/assets/img/lots/lot4_3.jpg"],
	customer: "Dmitry",
	totalCustomers: 2,
	finishDate: 3,
	category: "notebook",
	subCategory: "lenovo",
	description: "Alot information about different features"
	},
	{
	id: 5,
	name: "Iphone 7",
	currentPrice: 300,
	startPrice: 0,
	lastPrice: 100,
	img: [ "/assets/img/lots/lot5_1.jpg", "/assets/img/lots/lot5_2.jpg", "/assets/img/lots/lot5_3.jpg"],
	customer: "Vladimir",
	totalCustomers: 6,
	finishDate: 5,
	category: "phone",
	subCategory: "iphone",
	description: "Alot information about different features"
	},
	{
	id: 7,
	name: "Samsung QE55Q8",
	currentPrice: 4300,
	startPrice: 3000,
	lastPrice: 5000,
	img: [ "/assets/img/lots/lot7_1.jpg", "/assets/img/lots/lot7_2.jpg", "/assets/img/lots/lot7_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 6,
	finishDate: 5,
	category: "TV",
	subCategory: "curved",
	description: "Alot information about different features"
	},
	{
	id: 8,
	name: "Samsung QE55Q7",
	currentPrice: 4000,
	startPrice: 2000,
	lastPrice: 4800,
	img: [ "/assets/img/lots/lot8_1.jpg", "/assets/img/lots/lot8_2.jpg", "/assets/img/lots/lot8_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 5,
	finishDate: 3,
	category: "TV",
	subCategory: "curved",
	description: "Alot information about different features"
	},
	{
	id: 9,
	name: "Panasonic TX-40ESR500",
	currentPrice: 3600,
	startPrice: 3000,
	lastPrice: 5000,
	img: [ "/assets/img/lots/lot9_1.jpg", "/assets/img/lots/lot9_2.jpg", "/assets/img/lots/lot9_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 4,
	finishDate: 3,
	category: "TV",
	subCategory: "smart",
	description: "Alot information about different features"
	},
	{
	id: 10,
	name: "LG qt5613",
	currentPrice: 3000,
	startPrice: 2000,
	lastPrice: 4500,
	img: [ "/assets/img/lots/lot10_1.jpg", "/assets/img/lots/lot10_2.jpg", "/assets/img/lots/lot10_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 2,
	finishDate: 5,
	category: "TV",
	subCategory: "smart",
	description: "Alot information about different features"
	},
	      {
	id: 11,
	name: " Sony KD-43",
	currentPrice: 6000,
	startPrice: 4000,
	lastPrice: 8000,
	img: [ "/assets/img/lots/lot11_1.jpg", "/assets/img/lots/lot11_2.jpg", "/assets/img/lots/lot11_3.jpg"],
	customer: "ROZETKA UA",
	totalCustomers: 3,
	finishDate: 1,
	category: "TV",
	subCategory: "smart",
	description: "Alot information about different features"
	},
	{
	id: 12,
	name: "Samsung UE40M",
	currentPrice: 5000,
	startPrice: 2000,
	lastPrice: 8000,
	img: [ "/assets/img/lots/lot12_1.jpg", "/assets/img/lots/lot12_2.jpg", "/assets/img/lots/lot12_3.jpg"],
	customer: "Dmitry",
	totalCustomers: 2,
	finishDate: 5,
	category: "TV",
	subCategory: "smart",
	description: "Alot information about different features"
	},
	{
	id: 13,
	name: "LG 49LH609",
	currentPrice: 4000,
	startPrice: 2800,
	lastPrice: 9000,
	img: [ "/assets/img/lots/lot13_1.jpg", "/assets/img/lots/lot13_2.jpg", "/assets/img/lots/lot13_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 5,
	finishDate: 3,
	category: "TV",
	subCategory: "smart",
	description: "Alot information about different features"
	},
	{
	id: 14,
	name: "Meizu M5",
	currentPrice: 3000,
	startPrice: 2800,
	lastPrice: 3300,
	img: [ "/assets/img/lots/lot14_1.jpg", "/assets/img/lots/lot14_2.jpg", "/assets/img/lots/lot14_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 2,
	finishDate: 3,
	category: "phone",
	subCategory: "meizu",
	description: "Alot information about different features"
	},
	{
	id: 15,
	name: "Meizu M5 Note",
	currentPrice: 2000,
	startPrice: 1800,
	lastPrice: 2200,
	img: [ "/assets/img/lots/lot15_1.jpg", "/assets/img/lots/lot15_2.jpg", "/assets/img/lots/lot15_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 6,
	finishDate: 5,
	category: "phone",
	subCategory: "meizu",
	description: "Alot information about different features"
	},
	      {
	id: 16,
	name: "Redmi 4X",
	currentPrice: 5000,
	startPrice: 3000,
	lastPrice: 8000,
	img: [ "/assets/img/lots/lot16_1.jpg", "/assets/img/lots/lot16_2.jpg", "/assets/img/lots/lot16_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 3,
	finishDate: 1,
	category: "phone",
	subCategory: "redmi",
	description: "Alot information about different features"
	},
	{
	id: 17,
	name: "Redmi Note 5A",
	currentPrice: 3000,
	startPrice: 2000,
	lastPrice: 4000,
	img: [ "/assets/img/lots/lot17_1.jpg", "/assets/img/lots/lot17_2.jpg", "/assets/img/lots/lot17_3.jpg"],
	customer: "Dmitry",
	totalCustomers: 2,
	finishDate: 5,
	category: "phone",
	subCategory: "redmi",
	description: "Alot information about different features"
	},
	{
	id: 18,
	name: "Samsung A5",
	currentPrice: 250,
	startPrice: 200,
	lastPrice: 300,
	img: [ "/assets/img/lots/lot18_1.jpg", "/assets/img/lots/lot18_2.jpg", "/assets/img/lots/lot18_3.jpg"],
	customer: "Bob",
	totalCustomers: 5,
	finishDate: 3,
	category: "phone",
	subCategory: "samsung",
	description: "Alot information about different features"
	},
	{
	id: 19,
	name: "Samsung j7",
	currentPrice: 1500,
	startPrice: 1200,
	lastPrice: 3000,
	img: [ "/assets/img/lots/lot19_1.jpg", "/assets/img/lots/lot19_2.jpg", "/assets/img/lots/lot19_3.jpg"],
	customer: "Dmitry",
	totalCustomers: 2,
	finishDate: 3,
	category: "phone",
	subCategory: "samsung",
	description: "Alot information about different features"
	},
	{
	id: 20,
	name: "Samsung s8",
	currentPrice: 6000,
	startPrice: 4800,
	lastPrice: 12000,
	img: [ "/assets/img/lots/lot20_1.jpg", "/assets/img/lots/lot20_2.jpg", "/assets/img/lots/lot20_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 6,
	finishDate: 5,
	category: "phone",
	subCategory: "samsung",
	description: "Alot information about different features"
	},
	{
	id: 21,
	name: "Acer espite",
	currentPrice: 700,
	startPrice: 6000,
	lastPrice: 8000,
	img: [ "/assets/img/lots/lot21_1.jpg", "/assets/img/lots/lot21_2.jpg", "/assets/img/lots/lot21_3.jpg"],
	customer: "Rozetka UA",
	totalCustomers: 6,
	finishDate: 5,
	category: "Notebook",
	subCategory: "Acer",
	description: "Alot information about different features"
	},
    ];

    const users = [
      {	
		id: 1,
		username: "admin",
		firstname: "Dmitry",
		lastname: "Sulimov",
		email: "sulimovdmitryvnua@gmail.com",
		password: "Password",
		phone: "0632791303",
		isAdmin: true,
		currentBalance: 10000
		},
		{	
		id: 2,
		username: "user1",
		email: "user1@gmail.com",
		password: "Password",
		phone: "0632791301",
		isAdmin: false,
		currentBalance: 0
		},
		{	
		id: 3,
		username: "user2",
		firstname: "Dmitry",
		lastname: "Sulimov",
		email: "user2@gmail.com",
		password: "Password",
		phone: "0632791302",
		isAdmin: false,
		currentBalance: 200
		},
		{	
		id: 4,
		username: "Rozetka UA",
		firstname: "Rozetka",
		lastname: "admin",
		email: "admin@rozetka.ua",
		password: "Password",
		phone: "0677777777",
		isAdmin: false,
		currentBalance: 200000
		}
    ];
    return {lots, users};
  }
}